### ISSUE TITLE
Potential issue with SuccessrateSensor

### ISSUE THREAD

**Issue by bendiksolheim** [Espenhh/panopticon#11]
SuccessrateSensor threw an exception in our logs, and it seems it actually stopped the Panopticon client library from sending more data to the server. There was no stack trace, but the following text appeared in the logs:

- `Something went wrong when counting SUCCESS for ...`
- `ArrayIndexOutOfBoundsException: null`

**Comment by bendiksolheim** [comment]
Stacktrace:
```
p.panopticon.client.sensor.impl.SuccessrateSensor.tickSuccess[34] - Something went wrong when counting SUCCESS for xxxxxxxx
java.lang.ArrayIndexOutOfBoundsException: 100
	at org.apache.commons.collections4.queue.CircularFifoQueue.add(CircularFifoQueue.java:241) ~[commons-collections4-4.1.jar:4.1]
	at pro.panopticon.client.sensor.impl.SuccessrateSensor.tickSuccess(SuccessrateSensor.java:32) ~[panopticon-client-0.0.13.jar:na]
```
